name: secure_call_auth
description: A secure phone call authentication application using Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  
  # Encryption and security
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # Audio processing (for demo)
  just_audio: ^0.9.34
  
  # Utility packages
  permission_handler: ^10.4.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
